version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: "mysql:9.2.0"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=demo_proto
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379