// Code generated by Kitex v0.9.1. DO NOT EDIT.

package echo

import (
	server "github.com/cloudwego/kitex/server"
	spi "github.com/stigwang-gang/biz-demo/gomall/demo/demo_thrift/kitex_gen/spi"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler spi.Echo, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
